enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focus-changed = ['move-mouse window-lazy-center']

[mode.main.binding]

    alt-shift-c = 'reload-config'

    # alt-r = 'mode resize'

    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0
