set-option -g prefix C-b
set-option -g prefix2 C-a


set-option -g history-limit 100000
# SSH_CONNECTION is in the default list; sshd sets these too
set-option -ga update-environment "SSH_CLIENT SSH_TTY"
set -g default-terminal "${TERM}"
set-window-option -g mode-keys vi

# Automatic rename
set-option -g status-interval 2
set-option -g allow-rename on
set-option -g automatic-rename on
set-option -g renumber-windows on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g base-index 1
set -g focus-events on
set -g mouse on
# allow passthrough of notifications and such from claude code
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
